
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class OutputDesign extends javax.swing.JFrame {
    float awt, att;
    ArrayList<Event> events;
    Timer timer;
    /**
     * Creates new form output
     * @param awt
     * @param att
     * @param events
     * @throws java.lang.InterruptedException
     */
    public OutputDesign(float awt,float att,ArrayList<Event> events){
        initComponents();
        this.awt=awt;
        this.att=att;
        this.events=events;
        
        
    }
    
    public OutputDesign() {
        initComponents();
       
    }
//    public void printTime(){
//        System.out.println("inside output");
//        System.out.println(awt);
//        System.out.println(att);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lrun = new javax.swing.JLabel();
        awtL = new javax.swing.JLabel();
        attL = new javax.swing.JLabel();
        awtLabel = new javax.swing.JLabel();
        attLabel = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        Lrun.setBackground(new java.awt.Color(255, 153, 153));
        Lrun.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        Lrun.setForeground(new java.awt.Color(102, 0, 204));

        awtL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        awtL.setForeground(new java.awt.Color(0, 102, 102));
        awtL.setText("Average Waiting Time");

        attL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        attL.setForeground(new java.awt.Color(0, 102, 102));
        attL.setText("Average TurnaroundTime");

        awtLabel.setBackground(new java.awt.Color(255, 153, 204));
        awtLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        awtLabel.setForeground(new java.awt.Color(255, 0, 51));

        attLabel.setBackground(new java.awt.Color(255, 153, 204));
        attLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        attLabel.setForeground(new java.awt.Color(255, 0, 51));

        startBtn.setBackground(new java.awt.Color(204, 153, 255));
        startBtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 153, 51));
        startBtn.setText("Start Simulation");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(attL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(awtL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(awtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(Lrun, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lrun, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(awtL)
                    .addComponent(awtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attL)
                    .addComponent(attLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int current=0;
    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
              
        timer=new Timer((events.get(current).endTime-events.get(current).startTime)*1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 System.out.println(timer.getDelay());
                 System.out.println(current==events.size());
                if(current==events.size()-1){
                    Lrun.setText("Terminated");
                    timer.stop();
                    awtLabel.setText(String.valueOf(awt));
                    attLabel.setText(String.valueOf(att));
                    current=0;
                    
                }
                else{
                    System.out.println(events.get(current).startTime+events.get(current).id+events.get(current).endTime);
                    printLabel(events.get(current));
                    if(current!=events.size()-1){
                    timer.setDelay((events.get(current+1).endTime-events.get(current+1).startTime)*1000);
                    }                    
                    current++;
                    
                }
                
            }
        });
        
        timer.start();                
    }//GEN-LAST:event_startBtnActionPerformed

    public void printLabel(Event e){
        if(e.id=="Idle"){
           Lrun.setText("Idle");
        }
        else{
            Lrun.setText(e.id+" running");}
        
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lrun;
    private javax.swing.JLabel attL;
    private javax.swing.JLabel attLabel;
    private javax.swing.JLabel awtL;
    private javax.swing.JLabel awtLabel;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables

    
}
